server:
  port: ${SERVER_PORT}

spring:
  application:
    profiles:
      active: 'local'
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_DATABASE}
